<div id="contentArea">
	<h1>Central North Pacific Event Types</h1>
	<div class="content">
		<a name="tw"></a>
			<h2>Strong Trade Winds, Trade Wind Showers, and Trade Wind Swell (SW, HR, HS)</h2>
			<p>Seasonal: Summer (May to September)</p>
			<p>The northeasterly Trade winds are dominant feature of the weather and climate in the central North Pacific. The Trades are the most persistent regional wind pattern in the world; persistent here means consistency of direction, speed, and manifestation throughout the year.</p>
			<p>The Trades are generated by the <a href="index.php?page=glossary#nph">North Pacific High</a>, a center of high pressure, or anticyclone in the eastern North Pacific that spins in a clockwise direction and produces winds that spiral outward. In the Hawaiian Islands the Trade winds blow about 70% of the time. Typically they range from 5 to 10 meters per second (10 to 25 miles per hour). Occasionally, they reach 20+ meters per second (40+miles per hour).</p>
			<p>The pattern of the Trades is responsible for the broadest climatological features of the Hawaiian Islands. As cumulus clouds associated with the quasi-permanent sub-tropical high are constantly advected towards the islands, regions of maximum rainfall are usually located on northeast, windward slopes where orographic uplifting is most pronounced. On the southwest leeward side of the mountains, air sinks and warms, suppressing the development of rain showers there.</p>
			<p>During the summer the North Pacific High is larger, stronger, and centered farther north. As a result, the Trade winds are more frequent and intense - wind speeds over the ocean exceed 5 meters per second 50 percent of the time, and 80-95% of the time these winds are from the northeast quadrant. The favored season for Trade wind showers is June to August.</p>
			<p>Extremes in winds, rain, waves are not typical of summer Trade wind or "dry season" conditions. However, localized intense rainfall events, along with high waves, may occur along east-facing shores. These intense storms often develop in association with convergence from Trade winds and existing boundaries, either topographic or from sea-breezes. As Trade winds bump up against the topography, the airflow is directed upward, enhancing vertical motion and rainfall. However, once clouds reach the height of the Trade wind inversion, their growth is inhibited, and any locations situated above this inversion are far drier than their lower elevation counterparts.</p>
			<p>The interaction between local sea/land-breezes and Trade winds vary by time of day and island in Hawaii. For strong Trade winds, daily rainfall amounts on the windward side of Hilo are higher with a nocturnal maximum owing to convergence of the katabatic flow and the incoming decelerating Trade-wind flow, and orographic lift. This maximum rainfall axis generally shifts further inland as the Trade winds get stronger.</p>
			<p>During the winter the North Pacific High is smaller, weaker, and located farther south. Often disrupted by storms (cyclones) that drop down from mid-latitudes, the Trade winds are less frequent and less intense during this time - 50% of the wind in Hawaii during January is Trade wind breezes.</p>
			<p>During <a href="index.php?page=glossary#enso">El Ni&ntilde;o</a> conditions, strong surface westerly anomalies prevail over Hawaii. This weakens the easterly Trade winds, which corresponds to a reduction in Trade wind rainfall and, in turn dry and even drought conditions throughout the Hawaiian Islands. The opposite effects tend to occur during <a href="index.php?page=glossary#enso">La Ni&ntilde;a</a> conditions: that is, stronger Trade winds and increased rainfall.</p>
			<p>Other extreme event types of the central North Pacific include</p>
			<ul>
				<li><a href="#tc">Tropical Cyclones (Hurricanes) and Tropical Storms </a></li>
			    <li><a href="#lks">Local "Kona" Storms ("Sub-Tropical" Cyclones)</a></li>
			    <li><a href="#fs">Frontal Systems</a></li>
				<li><a href="#ull">Upper Level Lows</a></li>
				<li><a href="#etss">Extra-Tropical Storm Surf</a></li>
				<li><a href="#et">Extreme Tides</a></li>
			</ul>
		<a name="tc"></a>
			<h2>Tropical Cyclones (Hurricanes) and Tropical Storms (SW, HR, HS)</h2>
			<p>Seasonal: Summer (JAS, JASO, or June to October)</p>
			<p>Low pressure, cyclonic systems originating in the in near-equatorial oceans are known as tropical storms and, when they become powerful enough, <a href="index.php?page=glossary#tc">tropical cyclones</a>. Specifically, according to the <a href="index.php?page=glossary#tc">Saffir-Simpson scale</a>, a storm is referred to as a tropical depression when one-minute sustained wind speeds reach up to 38 miles per hour (17 meters per second), a tropical storm when wind speeds range from 39 to 73 miles per hour (17 to 32 meters per second), and a hurricane when winds exceed 73 miles per hour. When hurricane strength storms make landfall, the combination of fierce winds, intense rains, and high surf can be devastating (e.g., Iniki 1992).</p>
			<p>Most hurricanes entering Hawaiian waters develop over warm ocean waters in the eastern Pacific. Approaching the Hawaiian Islands from the east, they hit eastern shores and south- and west-facing shorelines as they pass to the south and west. Oftentimes, these storms trek westward and fill/decay, but they can also curve north to higher latitudes. On occasion, these intense storms do form in the central North Pacific hurricane region - a zone bounded by the equator and west longitude lines of 140&deg; and 180&deg;. These are given Hawaiian names as assigned by the <a href="http://www.prh.noaa.gov/hnl/cphc/" target="_blank">Central Pacific Hurricane Center (CPHC)</a>.</p>
			<p>Hurricanes are most likely to develop during the late summer or fall, when ocean temperatures are at a maximum. These relatively rare, but extreme events interrupt the summer Trade wind conditions. They constitute perhaps the most dramatic wind events in this region.</p>
			<p>Since 1966, 14 named storms have passed within 65 nautical miles of the state of Hawaii. This results in a frequency of one named storm passing near the island chain approximately once every three years.</p>
			<p>Climatologically there appear to be years during which these systems occur more frequently. During <a href="index.php?page=glossary#enso">El Ni&ntilde;o</a> conditions, there tends to be a higher frequency of hurricanes in the vicinity of Hawaii due to more tropical cyclone formation in the central North Pacific and a tendency for tropical cyclones originating in the eastern North Pacific to enter the central North pacific. The strong El Ni&ntilde;o years in 1982 and 1997, for example, are associated with a relative maximum number of occurrences (10 and 9, tropical cyclones respectively). It has also been reported that during El Ni&ntilde;o conditions tropical cyclones in the eastern North Pacific have a longer track toward the west than during non-El Ni&ntilde;o conditions.</p>
			<p>Tropical cyclone activity in the central North Pacific has been found to be on the rise over the period from 1966-97. This upward trend is characterized by decadal-scale variability as manifested by fewer cyclones during the first half of the record (1966-81) and more during the second half of the record (1982-97). The maximum hurricane intensity has also increased in the central North Pacific, as well as the number of intense hurricanes from the first to the second half of the record. The changes in the frequency and intensity of tropical cyclones in the central North Pacific appear to be modulated by decadal-scale variability of the basic state of SST, which transitioned from a cold to a warm phase of the <a href="index.php?page=glossary#pdo">Pacific Decadal Oscillation</a> (PDO) in the late 1970s.</p>
			<p>Hurricanes and tropical storms that pass in the vicinity of Hawaii are also important sources of <a href="index.php?page=glossary#sgw">waves</a> that impact the islands' coasts on an inter-annual basis. Waves from hurricanes and tropical storms can reach extreme heights (10 meters).The greatest threat of coastal flooding and erosion occurs when these waves combine with <a href="index.php?page=glossary#ss">storm surge</a> and high <a href="index.php?page=glossary#tides">tides</a>.</p>
			<p>Other extreme event types of the central North Pacific include</p>
			<ul>
				<li><a href="#tw">Strong Trade Winds, Trade Wind Showers, and Trade Wind Swell </a></li>
			    <li><a href="#lks">Local "Kona" Storms ("Sub-Tropical" Cyclones)</a></li>
			    <li><a href="#fs">Frontal Systems</a></li>
				<li><a href="#ull">Upper Level Lows</a></li>
				<li><a href="#etss">Extra-Tropical Storm Surf</a></li>
				<li><a href="#et">Extreme Tides</a></li>
			</ul>
		<a name="lks"></a>
			<h2>Local "Kona" Storms (&quot;Sub-Tropical&quot; Cyclones) (SW, HR, HS)</h2>
			<p>Seasonal: Winter and Spring (OND and JFM, or October-May)</p>
			<p>Kona (the Hawaiian word for leeward) are a particular type of low pressure system, a "cut-off low", in which the surface system is separated to the south from the main pathway of the westerlies and so loses positive steering. With their origin in the high altitudes of the sub-tropics Kona lows are classified as &quot;sub-tropical&quot; cyclones. These hybrid systems are vertically stacked, which is a tropical characteristic, and the forcing is of tropical origin (barotropic instability).However they have cold cores like extra-tropical cyclones, although they don&#39;t have the horizontal gradient that typifies mid-latitude systems and is the source of their instability (baroclinic instability).Kona storms are a significant cause of flooding in the Hawaiian Islands.</p>
			<p>Typified by winds and rain arriving from the direction opposite from the Trade winds, these conditions are a characteristic feature of the winter "wet season" in the central North Pacific. Kona storms vary in number from year to year. An entire winter may pass without a single well-developed Kona storm.&nbsp; More often, however, there are two or three such storms a year, and sometimes there are five or more. Kona storms reach a maximum during October and November, with a secondary peak in February. Occasionally, Kona storms develop during the summer.</p>
			<p>Kona storms tend to develop northwest or west of the Hawaiian Islands and move slowly eastward. If close enough, the archipelago is entrained in the counterclockwise flow. These southerly winds, which can reach 22 meters per second (50 miles per hour), can also bring heavy downpours. Kona rains last from several hours to several days.&nbsp; The rains may continue steadily, but the longer lasting ones are characteristically interrupted by intervals of lighter rain or even partial clearing, as well as by intense showers superimposed upon the more moderate regime of continuous, steady rain. The rainfall in a well-developed Kona storm is more widespread and more prolonged than in the usual cold-front storm; more prolonged, and not as strong as the more extreme winds of the cold front.&nbsp; Kona storm rains are usually most intense in an arc, or band, extending from south to east of the storm and well in advance of its center.</p>
			<p><a href="index.php?page=glossary#enso">El Ni&ntilde;o</a> and positive/warm phase <a href="index.php?page=glossary#pdo">Pacific Decadal Oscillation</a> (PDO) conditions tend to inhibit the development and maintenance of sub-tropical cyclones over Hawaii. The conditions are associated with relatively low rainfall and drought.</p>
			<p>High <a href="index.php?page=glossary#sgw">waves</a> are typically not a concern during Kona storms. Kona storm swell is characterized by waves of moderate height (3 meters) and short to moderate periods (8-10 seconds). These 'steep' waves have their greatest impact on coasts that face south and west.</p>
			<p>Other extreme event types of the central North Pacific include</p>
			<ul>
				<li><a href="#tw">Strong Trade Winds, Trade Wind Showers, and Trade Wind Swell </a></li>
				<li><a href="#tc">Tropical Cyclones (Hurricanes) and Tropical Storms </a></li>
			    <li><a href="#fs">Frontal Systems</a></li>
				<li><a href="#ull">Upper Level Lows</a></li>
				<li><a href="#etss">Extra-Tropical Storm Surf</a></li>
				<li><a href="#et">Extreme Tides</a></li>
			</ul>
		<a name="fs"></a>
			<h2>Frontal Systems (SW, HR, HS)</h2>
			<p>Seasonal: late Winter to early Spring (JFM or December-March)</p>
			<p>Cold fronts mark the leading edges of cold air masses associated with low-pressure systems moving north of the Hawaiian Islands in the prevailing westerlies. These fronts and mid-latitude cyclones bring clouds and light to moderate precipitation with winds from the northeast through the northwest. However, when they translate south and move closer to the Hawaiian Islands or pass directly over them and disrupt the Trade winds, heavy rains accompanied by southwest winds may occur.</p>
			<p>Heavy rains can occur along the frontal zone with a southerly component to the low-level winds, or behind the frontal zone with a northerly low-level wind component. Fronts often bring a substantial fraction of the winter rainfall to the islands, perhaps the largest percentage of any synoptic-scale feature. Frontal rainfall is commonly enhanced by its passage over the higher terrain, which escalates upward vertical velocities and the process of rain generation.</p>
			<p>Typically these rains are spotty, with several inches falling in some areas and only fractions of an inch in others.&nbsp; Winds are gusty, with wind directions mainly from the north and northwest.&nbsp; The cool air that follows the passage of the front brings relatively cloudless skies. Perhaps once every three or four years on the average a cold front storm will produce winds that blow down trees or rip the roofs from houses within a limited area of a square mile or so.&nbsp;</p>
			<p>Cold fronts are common between the months of October and April, the winter "wet season" in the Hawaiian Islands. During some winter seasons as many as six or eight well-defined cold fronts may sweep across two or more islands of the State.&nbsp; During others, there may be only one or two.&nbsp;Frontal storms usually occur during the period from December through March. January is the peak month for frontal passages, followed by December. Because of its location at the northwest end of Hawaii, the Island of Kauai has a few more cold front storms each year than do Oahu and the other islands.</p>
			<p>The frequency of passage of fronts is responsible for wet and dry years in leeward regions, which receive much of their rainfall from fronts. <a href="index.php?page=glossary#enso">El Ni&ntilde;o</a> and positive/warm phase <a href="index.php?page=glossary#pdo">Pacific Decadal Oscillation</a> (PDO) conditions tend to inhibit the the southeastward propagation of strong frontal systems over Hawaii. The conditions are associated with relatively low rainfall and drought.</p>
			<p>Other extreme event types of the central North Pacific include</p>
			<ul>
				<li><a href="#tw">Strong Trade Winds, Trade Wind Showers, and Trade Wind Swell </a></li>
				<li><a href="#tc">Tropical Cyclones (Hurricanes) and Tropical Storms </a></li>
			    <li><a href="#lks">Local "Kona" Storms ("Sub-Tropical" Cyclones)</a></li>
				<li><a href="#ull">Upper Level Lows</a></li>
				<li><a href="#etss">Extra-Tropical Storm Surf</a></li>
				<li><a href="#et">Extreme Tides</a></li>
			</ul>
		<a name="ull"></a>
			<h2>Upper Level Lows (SW, HR, HS)</h2>
			<p>Seasonal: late Winter to early Spring (JFM or December-March)</p>
			<p>Severe weather in the Hawaiian Island is at times attributable to low pressure areas which are well developed in the upper atmosphere (rather than near sea level) and are not related to cold fronts, Kona storms or tropical storms.&nbsp; The weather which accompanies these upper Lows or trough - towering cumulus clouds, thunderstorms, intense and widespread rain - often resembles that of a Kona storm and may be mistaken for one, except for the absence of the persistence, and sometimes strong, southerly winds that frequently accompany Kona storms.&nbsp; The surface winds during these events may be from almost any direction, and are often associated with low pressure aloft.</p>
			<p>Upper level lows can occur any time of the year. Extreme weather from the upper level low-pressure system can have the longest duration of any major storm type because the system is large and moves or weakens slowly.</p>
			<p>Other extreme event types of the central North Pacific include</p>
			<ul>
				<li><a href="#tw">Strong Trade Winds, Trade Wind Showers, and Trade Wind Swell </a></li>
				<li><a href="#tc">Tropical Cyclones (Hurricanes) and Tropical Storms </a></li>
			    <li><a href="#lks">Local "Kona" Storms ("Sub-Tropical" Cyclones)</a></li>
			    <li><a href="#fs">Frontal Systems</a></li>
				<li><a href="#etss">Extra-Tropical Storm Surf</a></li>
				<li><a href="#et">Extreme Tides</a></li>
			</ul>
		<a name="etss"></a>
			<h2>Extra-Tropical Storm Surf (HS)</h2>
			<p>Seasonal: Winter (November-February) and Summer (April-September)</p>
			<p>Extra-tropical storms are formed at relatively high latitudes by cold air masses moving down from sub-polar regions and colliding with warmer air masses. The impact of long period swells generated from these distant storms can be felt in the Hawaiian Islands. The greatest threat of coastal flooding and erosion occurs when these high <a href="index.php?page=glossary#sgw">waves</a> combine with high <a href="index.php?page=glossary#tides">tides</a>.</p>
			<p>North Pacific swell delivers the highest waves annually (3 to 6+ meters in height).Characterized by moderate- to long-wave periods (10-18 seconds), North Pacific swell occurs throughout the year. However, it is most common during the winter when the strongest storms develop in the sub-polar and mid-latitudes of the northern North Pacific. It has the greatest impact on north-facing shores.&nbsp;&nbsp;</p>
			<p>South Pacific swell can occur anytime of the year, but is most common during the summer. During this time, winter storms develop in the Southern Hemisphere and send waves great distances across the Pacific to Hawaii. Characterized by very long wave periods (14-22 seconds), their greatest impact is felt along south-facing shores.</p>
			<p>Other extreme event types of the central North Pacific include</p>
			<ul>
				<li><a href="#tw">Strong Trade Winds, Trade Wind Showers, and Trade Wind Swell </a></li>
				<li><a href="#tc">Tropical Cyclones (Hurricanes) and Tropical Storms </a></li>
			    <li><a href="#lks">Local "Kona" Storms ("Sub-Tropical" Cyclones)</a></li>
			    <li><a href="#fs">Frontal Systems</a></li>
				<li><a href="#ull">Upper Level Lows</a></li>
				<li><a href="#et">Extreme Tides</a></li>
			</ul>
		<a name="et"></a>
			<h2>Extreme Tides (HS)</h2>
			<p>Seasonal: Winter Solstice (December or November-January) and Summer Solstice (June or May-July)</p>
			<p>Sea level variations in the Hawaiian Islands are modest in amplitude on most time scales owing to the moderate wind forcing and tidal variation in the region. Hawaii has two high tides and two low tides per day (semidiurnal).The average daily tidal range is ~0.6 m (microtidal) and seasonal, inter-annual, and decadal sea level fluctuations are on the order of ten of centimeters.</p>
			<p>Hawaii experiences boreal spring tides twice a month, and one of the two spring tides is stronger than the other because the moon is closer to the earth. Tides in the Hawaiian Islands reach their annual peak at the winter and summer solstices, in June and December, when the sun is at its maximum declination relative to the equator.&nbsp;&nbsp; Combined with <a href="index.php?page=glossary#oe">mesoscale "anticyclonic" eddies</a> as well as high <a href="index.php?page=glossary#sgw">waves</a> and <a href="index.php?page=glossary#ss">storm surge</a>, this semi-annual cycle plays an important role in controlling extreme water levels observed at the shoreline.</p>
			<p>Mesoscale eddies, here refer to the clockwise-rotating motions of fluid with diameters of up to several hundred kilometers and elevated water levels anywhere from a few to more than 15 centimeters. In the Pacific basin, eddies commonly form leeward of the Hawaiian Islands and move westward toward the Asian continent, but eddies also form windward of the islands, sometimes as far east as the waters off the coast of Mexico. It is the latter that have the greatest impact in the Hawaiian Islands. However, because most eddies form leeward of the islands, the Hawaiian Islands have only experienced 10 "eddy events" with heights of 15 centimeters or higher in the past decade. They have also been shown to contribute to sea level variability at Wake Island, farther to the west. These eddies move at speeds of around 6 cm/s, or roughly one half kilometer per day. Eddies at low latitudes move faster than eddies in higher latitudes, so depending on the eddy's location latitudinally, it could take anywhere from several months to several years to make a complete journey across the Pacific. There appears to be no preferred seasonal pattern associated with when these eddies - they arrive at the Hawaiian Islands any time of the year.</p>
			<p>Tidal and other fluctuations in water level are superimposed on a long-term upward trend which has increased mean <a href="index.php?page=glossary#gsl">global sea level</a> by approximately 15 cm over the past century. This rising background level contributes to a growing concern over anomalously high (10-20 cm) events on short (days to weeks) time-scales -especially when combined with high tides.</p>
			<p>Other extreme event types of the central North Pacific include</p>
			<ul>
				<li><a href="#tw">Strong Trade Winds, Trade Wind Showers, and Trade Wind Swell </a></li>
				<li><a href="#tc">Tropical Cyclones (Hurricanes) and Tropical Storms </a></li>
			    <li><a href="#lks">Local "Kona" Storms ("Sub-Tropical" Cyclones)</a></li>
			    <li><a href="#fs">Frontal Systems</a></li>
				<li><a href="#ull">Upper Level Lows</a></li>
				<li><a href="#etss">Extra-Tropical Storm Surf</a></li>
			</ul>
		</div>
</div>
