<div id="contentArea">

  <h1>Western North Pacific Climatology Overview</h1>
  <h1 class="thin">(Micronesia)</h1>
  <div class="content">
        <div style="float:right; width: 300px;">
            <img width="300" src="images/overview/western-01.png"/>
		</div>
		<p>Weather in Micronesia is affected by several large-scale features of the tropical and subtropical general circulation: the belt of subtropical high pressure and its associated trade winds, the trade wind trough (also known in other regions as the ITCZ), and the East Asian and Western Pacific monsoon system.  The western North Pacific is the most active tropical cyclone basin.  The effects of ENSO are pronounced in this core region of this basin-wide climate cycle, and affect almost every aspect of the region's climate, including the rainfall, the typhoon distribution, and the sea level.</p>
        <div style="text-align: center;">
            <img width="575" src="images/overview/western-02.png"/>
            <p class="imgcaption">Some of the major island groups of Micronesia superimposed on a satellite mapping mean annual rainfall</p>
        </div>
		<p>There is a distinct seasonality to the weather of Micronesia, with the year being divided into the "rainy season" and the "dry season".  The relative length and strength of these two seasons is dependent on latitude, with the dry season longer and drier at locations further to the north.  For example, the dry season on Guam (13.5&deg; N) extends from about December through June when monthly rainfall values fall to approximately 5 inches or less.  The rainy season extends from July through November when monthly rainfall values are at or above 10 inches.  On Pohnpei Island (6.9&deg; N), there is only one month (February) when a pronounced drop in rainfall is typically experienced, with abundant rainfall throughout all the other months.  El Ni&ntilde;o has a substantial influence on the rainfall of Micronesia primarily via its influence on the duration and severity of the dry season.  Despite average annual rainfall totals of 100 inches (~2.5 m) or more, extended dry periods (usually related to El Ni&ntilde;o) cause many problems throughout Micronesia, and can quickly become life-threatening, even after only a month or two of negligible rainfall.</p>
		<p><a href="index.php?page=events-wnp#tw">Strong Trade Winds and Trade Wind Swell</a> are a characteristic feature of the weather throughout most of Micronesia.  Trade winds dominate the low level wind flow across most of Micronesia for roughly half of the year (December through June).  Trade winds are stronger and last longer at locations that are further north and/or east.  Because of their long fetch distances from near Hawaii into Micronesia, episodes of enhanced trade winds generate high surf.</p>
		<p>The monsoon trough episodically extends across Micronesia bringing southwesterly winds to the islands.  Gusty southwesterly winds for extended periods of time (days to a week or two) are typical from mid-July through mid-October.  Southwesterly winds are more persistent at locations to the south and west (e.g., Palau), are episodic on Guam (north central Micronesia), and occur rarely in Majuro (eastern Micronesia).  El Ni&ntilde;o affects the seasonality, distribution, and intensity of <a href="index.php?page=events-wnp#swm">The Southwest Monsoon and Monsoon Squalls in Micronesia</a>.</p>
		<p><a href="index.php?page=events-wnp#tc">Tropical Cyclones (Typhoons), tropical storms, and tropical depressions</a> traverse Micronesia every year.  They are most common between the months of July and December.  They may, however, be experienced at any time of the year.  Damaging typhoons have been experienced at most islands of Micronesia.  Hazards from typhoons include destructive winds, hazardous surf, coastal inundation, very heavy rainfall, and sea salt deposition.</p>
		<p><a href="index.php?page=events-wnp#ott">Other types of Thunderstorms</a> are common in Micronesia, particularly during the rainy season.  On the night of 20-21 April 1997, heavy rainfall triggered 30 landslides which resulted in 19 fatalities and the destruction of 14 dwellings in the villages of Oumoar and Iohl on the northwest side of the Island in the municipality of Sohkes, Pohnpei Island.</p>
		<p>In addition to high seas caused by tropical cyclones, monsoon surges and enhanced trade winds, the affects of distant storms can also be felt in the islands.  During the winter <a href="index.php?page=events-wnp#etss">Extra-tropical Storm Surf</a> can impact north-facing shores.  Intense extra-tropical storm systems that race eastward from the east China shore and Japan during winter generate large swell that moves in a generally southeastward direction.  Breaking surf of 15 to 20 feet is sometimes observed on the northern exposed beaches and reefs.  Damaging inundation has occurred with such episodes of swell. </p>
		<p><a href="index.php?page=events-wnp#et">Extreme Tides</a>, which tend to occur around the winter and summer solstices (December and June), are also relevant with respect to high seas.  Extreme tides have the greatest impact when they occur in conjunction with other phenomena such monsoon, trade-wind or storm waves, and during strong La Ni&ntilde;a conditions which can raise the local sea level by almost one foot.</p>
        <p>For a more detailed discussion of the Extremes Climatology of the western North Pacific go to:</p>
		<ul>
			<li><a href="index.php?page=events-wnp#tw">Strong Trade Winds and Trade Wind Swell</a></li>
			<li><a href="index.php?page=events-wnp#swm">The Southwest Monsoon and Monsoon Squalls</a></li>
			<li><a href="index.php?page=events-wnp#tc">Tropical Cyclones (Typhoons) , tropical storms, and tropical depressions</a></li>
			<li><a href="index.php?page=events-wnp#ott">Other types of Thunderstorms</a></li>
			<li><a href="index.php?page=events-wnp#etss">Extra-tropical Storm Surf</a></li>
			<li><a href="index.php?page=events-wnp#et">Extreme Tides</a></li>
		</ul>
		<p>See <a href="index.php?page=glossary">the glossary</a> for more information about some of the key atmospheric and oceanographic features that affect extreme winds, rainfall, waves and water levels in the Pacific.  </p> 
  </div>
</div>