<div id="contentArea">

    <h1>Central South Pacific Overview</h1>
    <h1 class="thin">(Polynesia to the northeast coast Australia)</h1>
    <div class="content">
        <div style="float:right; width: 480px; padding: 0px 40px 0px 0px">
            <img width="480" src="images/overview/csp1.jpg" alt="Map of Central South Pacific"/>
        </div>
        <p>The tropical southwest Pacific Ocean basin is an extremely large area of the globe encompassing an area of about 10 million square nautical miles and here defined as the area from longitude 135º East in Australia’s Gulf of Carpentaria and west to approximately 120º West longitude. This includes French Polynesia and the well known Pitcairn Island. The tropical extent of the basin stretches from the equator south to 25º South latitude.</p>
        <div style="float:left; width: 150px; padding: 10px 10px 0px 0px">
            <img src="images/overview/csp2.png" alt="Polynesion life."/>
        </div>
        <p>The ecosystems and economies of small islands of the tropical Southwest Pacific region are widely agreed to be among the most vulnerable in the world to climate variability. The region is particularly vulnerable to weather and climate extremes, such as <a href="#cyclones">Tropical Cyclones (TC)</a>, and to the exacerbation of existing hazards by climate change. The small island states of this region share a number of distinctive characteristics that serve to increase their sensitivity and vulnerability to climate variability. Apart from their small physical size, they are: (1) surrounded by large expanses of ocean; (2) highly prone to natural disasters; particularly extreme events such as tropical cyclones and droughts, and (3) relatively isolated from world economic markets.  All of these factors make the region highly sensitive to natural disasters, and are magnified by high population growth rates and densities; poorly developed infrastructures; and limited natural, financial and human resources.  Since 1950, for example, natural disasters have affected more than 3.4 million people and caused over 1,700 reported fatalities in the region, excluding Papua New Guinea, and TCs accounted for 76% of the reported disasters from 1950 to 2004.</p>
        <p>The southwest Pacific Ocean basin is important from a global climate standpoint as it is the home of <a href="index.php?page=glossary#enso">El Niño and La Niña</a> and the periodic shift between these conditions has impacts worldwide. There are several Niño regions or indices in the Pacific, and the one most important to determining weather and climate patterns in the region is known as Niño 3.4; using this index, 55% of the time there is either an El Niño or La Niña underway and only 45% of the time is one not present. Another important climatological feature in the region is known as the South Pacific Convergence Zone (SPCZ). The SPCZ is one of the most significant features of subtropical Southern Hemisphere climate.  It is characterized by a band of low-level convergence, cloudiness and precipitation in the western Pacific extending south eastwards towards French Polynesia.  Its location varies in relation to another feature in the region known as the Interdecadal Pacific Oscillation (IPO) as well as how the coupled El Nino Southern Oscillation (ENSO) is behaving at any one time. </p>
        <p><a id="cyclones"></a><span style="font-weight: 600">Tropical Cyclones (Hurricanes) and tropical storms</span> (SW, HR, HS) <br />
            Seasonal: Arboreal Summer (JFM, November to April)</p>
        
         <div style="float:right; width: 200px; padding: 0px 40px 0px 20px">
            <img src="images/overview/csp3.png" alt="Cyclone" />
        </div>
        <p>Given the vast expanse of the region, the documentation of Tropical Cyclones (TC) in this basin has been difficult. While there has been some considerable work done in documenting TCs in the Southwest Pacific Basin, it was not until the data was made more easily available and in convenient formats at a centralized, secure location in line with the work of the International Best Tracks for Climate Stewardship, that this consolidation work began. Following on to and building on the IBTrACS, a recent new dataset known as the South Pacific Enhanced Archive of Tropical Cyclones (SPEArTC) has also emerged to help better characterize TCs in the region; for example for the 30-year period from 1981-2010, there are an average of 12.33 TCs per season in the region, and the height of the season is from January to March. In the Southern Hemisphere, the TC season straddles the change of the calendar year; therefore, the 1970 season extends from November 1969 through April 1970, and the season is thus labeled as 1970. The 1970 TC season is generally considered to be the first reliable year due to the availability of geostationary satellite data.</p>
        <p>The IBTrACS dataset is available on-line <a href="http://www.ncdc.noaa.gov/oa/ibtracs/">here</a>, and the SPEArTC dataset is available on-line <a href="http://apdrc.soest.hawaii.edu/projects/speartc">here</a>.</p>
    </div>
</div>